### ISSUE TITLE
Feature request: GdipSaveImageToFile

### ISSUE THREAD

**Issue by Oldes** [qtxie/red#3]
Hi,
could you please also include `GdipSaveImageToFile` routine so we could already also save images? I'm quite not sure what is the best way how to deal with CLSID in Red.

Thanks.

**Comment by qtxie** [comment]
FYI: https://msdn.microsoft.com/en-us/library/windows/desktop/ms535407%28v=vs.85%29.aspx

**Comment by Oldes** [comment]
I know, but I'm not good enough yet to know, how to use Windows object like `Image` from Red. And even you used the flat API to load image.
