### ISSUE TITLE
CFNetwork error using the MacOSX-GUI branch

### ISSUE THREAD

**Issue by iArnold** [qtxie/red#4]
I am still on MacOSX 10.6.8
Compiling my program with the MacOSX-GUI branch is ok but running it results in an error: 
dyld: Library not loaded: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
  Referenced from: /Users/Arnold/..../Red/red-MacOSX-GUI/./macosx
  Reason: image not found
Trace/BPT trap

The only reference I have is in a Python documentation map (I think that came preinstalled).

**Comment by iArnold** [comment]
I have a CFNetwork on my system it is located here
 /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CFNetwork.framework/Versions/A/CFNetwork

**Comment by qtxie** [comment]
Thanks for reporting it. Should be fixed now.
